//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailClient.DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailClient.DAL.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al castear el tipo de entidad referenciado por el dbset del repositorio..
        /// </summary>
        internal static string CastOperationException {
            get {
                return ResourceManager.GetString("CastOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de crear la colección de entidades en la base de datos..
        /// </summary>
        internal static string CreateEntitiesException {
            get {
                return ResourceManager.GetString("CreateEntitiesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de crear una entidad en la base de datos..
        /// </summary>
        internal static string CreateEntityException {
            get {
                return ResourceManager.GetString("CreateEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de obtener las entidades de la base de datos..
        /// </summary>
        internal static string GetAllEntitiesException {
            get {
                return ResourceManager.GetString("GetAllEntitiesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de obtener la entidad de la base de datos. Verifique que el criterio de filtrado no genere más de un resultado..
        /// </summary>
        internal static string GetSingleEntityException {
            get {
                return ResourceManager.GetString("GetSingleEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de eliminar la entidad de la base de datos..
        /// </summary>
        internal static string RemoveEntityException {
            get {
                return ResourceManager.GetString("RemoveEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de preservar los datos en la base de datos. Verifique que no existan problemas con la conexión..
        /// </summary>
        internal static string SavingContextException {
            get {
                return ResourceManager.GetString("SavingContextException", resourceCulture);
            }
        }
    }
}
