//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailClient.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailClient.BLL.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Decrypt_FailOnDecrypt {
            get {
                return ResourceManager.GetString("Decrypt_FailOnDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Encrypt_FailOnEncrypt {
            get {
                return ResourceManager.GetString("Encrypt_FailOnEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar verificar la cuenta con los datos argumentados. Verifique que los datos son correctos..
        /// </summary>
        internal static string LoginException {
            get {
                return ResourceManager.GetString("LoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se desconoce el protocolo de comunicación.
        /// </summary>
        internal static string MailService_GetCommunicationProtocol_UnknownComunicationProtocol {
            get {
                return ResourceManager.GetString("MailService_GetCommunicationProtocol_UnknownComunicationProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailService_GetMailServiceByHostName_FailOnGetServiceByName {
            get {
                return ResourceManager.GetString("MailService_GetMailServiceByHostName_FailOnGetServiceByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailService_Retrieve_FailOnRetrieve {
            get {
                return ResourceManager.GetString("MailService_Retrieve_FailOnRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailService_Retrieve_OffsetOrWindowLessThanZero {
            get {
                return ResourceManager.GetString("MailService_Retrieve_OffsetOrWindowLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailService_Retrieve_OffsetSameOrLessThanWindow {
            get {
                return ResourceManager.GetString("MailService_Retrieve_OffsetSameOrLessThanWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailService_Send_FailOnSend {
            get {
                return ResourceManager.GetString("MailService_Send_FailOnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3_FetchNFirst_FailOnFetching {
            get {
                return ResourceManager.GetString("Pop3_FetchNFirst_FailOnFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3_FetchNFirst_UnknownErrorException {
            get {
                return ResourceManager.GetString("Pop3_FetchNFirst_UnknownErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3_Retrieve_FailOnFetching {
            get {
                return ResourceManager.GetString("Pop3_Retrieve_FailOnFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3_Retrieve_UnknownErrorException {
            get {
                return ResourceManager.GetString("Pop3_Retrieve_UnknownErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3ClientExtension_Authentication_FailOnAuth {
            get {
                return ResourceManager.GetString("Pop3ClientExtension_Authentication_FailOnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3ClientExtension_Connection_FailOnConnect {
            get {
                return ResourceManager.GetString("Pop3ClientExtension_Connection_FailOnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3ClientExtension_GetWindowedMessages_FailOnGettingMessages {
            get {
                return ResourceManager.GetString("Pop3ClientExtension_GetWindowedMessages_FailOnGettingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no se encuentra conectado.
        /// </summary>
        internal static string Pop3ClientExtension_GetWindowedMessages_ImNotConnectedException {
            get {
                return ResourceManager.GetString("Pop3ClientExtension_GetWindowedMessages_ImNotConnectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pop3ClientExtension_GetWindowedMessages_UnknownErrorException {
            get {
                return ResourceManager.GetString("Pop3ClientExtension_GetWindowedMessages_UnknownErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar registrar la cuenta..
        /// </summary>
        internal static string RegisterException {
            get {
                return ResourceManager.GetString("RegisterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Smtp_CreateMessage_FailOnCreateMessage {
            get {
                return ResourceManager.GetString("Smtp_CreateMessage_FailOnCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Smtp_SendMessage_FailOnSend {
            get {
                return ResourceManager.GetString("Smtp_SendMessage_FailOnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Smtp_SendMessage_UnknownErrorException {
            get {
                return ResourceManager.GetString("Smtp_SendMessage_UnknownErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SmtpClientExtension_SendMail_FailOnSend {
            get {
                return ResourceManager.GetString("SmtpClientExtension_SendMail_FailOnSend", resourceCulture);
            }
        }
    }
}
