//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailClient.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailClient.Core.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error durante el inicio de sesión. Vea excepción interna..
        /// </summary>
        internal static string LoginException {
            get {
                return ResourceManager.GetString("LoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los valores argumentados durante la operación de inicio de sesión no pueden ser nulos..
        /// </summary>
        internal static string LoginNullOrEmptyArgumentException {
            get {
                return ResourceManager.GetString("LoginNullOrEmptyArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error durante la instanciación de la aplicación..
        /// </summary>
        internal static string MCCoreIntantiateException {
            get {
                return ResourceManager.GetString("MCCoreIntantiateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error durante el registro de la cuenta de correo. Vea excepción interna..
        /// </summary>
        internal static string RegisterException {
            get {
                return ResourceManager.GetString("RegisterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error durante el proceso de envío de correo. Vea excepción interna..
        /// </summary>
        internal static string SendException {
            get {
                return ResourceManager.GetString("SendException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error durante el proceso de actualización de la casilla de correos. Vea excepción interna..
        /// </summary>
        internal static string UpdateInboxException {
            get {
                return ResourceManager.GetString("UpdateInboxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccount_GetMailService_FailOnGetMailService {
            get {
                return ResourceManager.GetString("UserAccount_GetMailService_FailOnGetMailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccount_Send_FailOnSend {
            get {
                return ResourceManager.GetString("UserAccount_Send_FailOnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccount_UknownErrorException {
            get {
                return ResourceManager.GetString("UserAccount_UknownErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccount_UpdateInbox_FailOnUpdateInbox {
            get {
                return ResourceManager.GetString("UserAccount_UpdateInbox_FailOnUpdateInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_GetUser_FailOnGetUser {
            get {
                return ResourceManager.GetString("UserAccountController_GetUser_FailOnGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_GetUser_NoUserAccountsFound {
            get {
                return ResourceManager.GetString("UserAccountController_GetUser_NoUserAccountsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_GetUser_UknownMailAccount {
            get {
                return ResourceManager.GetString("UserAccountController_GetUser_UknownMailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_NewUser_ExistingMailAccount {
            get {
                return ResourceManager.GetString("UserAccountController_NewUser_ExistingMailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_NewUser_FailOnNewUser {
            get {
                return ResourceManager.GetString("UserAccountController_NewUser_FailOnNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_UknownErrorException {
            get {
                return ResourceManager.GetString("UserAccountController_UknownErrorException", resourceCulture);
            }
        }
    }
}
